---
# tasks file for eks
- debug: msg="Starting role eks v0.1.0"

- include_tasks: create.yml
  when: eks_cluster_state == "present"

- include_tasks: remove.yml
  when: eks_cluster_state == "absent"
