---
# tasks file for eks
- debug: msg="Starting cluster teardown..."

- name: Remove the EKS cluster
  aws_eks_cluster:
    name: "{{ eks_cluster_name }}"
    region: "{{ eks_cluster_region }}"
    state: absent
    wait: yes       # currently ignored so chances are the rest will fail :(
                    # PR in to hopefully make this better

- name: Remove worker security group
  ec2_group:
    name: "{{ eks_worker_sg_name }}"
    vpc_id: "{{ eks_cluster_vpc }}"
    region: "{{ eks_cluster_region }}"
    state: absent

- name: Remove control plane security group
  ec2_group:
    name: "{{ eks_control_sg_name }}"
    vpc_id: "{{ eks_cluster_vpc }}"
    region: "{{ eks_cluster_region }}"
    state: absent

- name: Create a role with description
  iam_role:
    name: "{{ eks_cluster_name }}-eks-role"
    state: absent

